packages:
  - lint
  - commitlint
  - tsconfig
  - design
  - utils
  - web

catalog:
  '@antfu/eslint-config': ^3.8.0
  '@changesets/cli': ^2.27.9
  '@commitlint/cli': ^19.5.0
  '@commitlint/config-conventional': ^19.5.0
  '@ctrl/tinycolor': ^4.1.0
  '@iconify-json/carbon': ^1.2.4
  '@prettier/plugin-xml': ^3.4.1
  '@types/node': ^22.9.4
  '@unocss/eslint-plugin': ^0.64.0
  '@vitejs/plugin-vue': ^5.2.0
  '@vitejs/plugin-vue-jsx': ^4.1.0
  '@vueuse/core': ^12.0.0
  '@iconify/tools': ^4.0.7
  '@iconify/utils': ^2.1.33
  postcss: ^8.4.49
  czg: ^1.11.0
  eslint: ^9.14.0
  eslint-plugin-format: ^0.1.2
  lint-staged: ^15.2.10
  naive-ui: ^2.40.2
  simple-git-hooks: ^2.11.1
  theme-colors: ^0.1.0
  typescript: ^5.6.3
  unocss: ^0.64.1
  vite: ^5.4.11
  vite-plugin-dts: ^4.3.0
  vue: ^3.5.13
